# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ergodic_sim <- function(agents, rounds, money, win, loss) {
    .Call(`_misccpp_ergodic_sim`, agents, rounds, money, win, loss)
}

choose_cpp <- function(n, k) {
    .Call(`_misccpp_choose_cpp`, n, k)
}

combn_cpp <- function(x, K) {
    .Call(`_misccpp_combn_cpp`, x, K)
}

rep_times <- function(x, n) {
    .Call(`_misccpp_rep_times`, x, n)
}

rep_each <- function(x, n) {
    .Call(`_misccpp_rep_each`, x, n)
}

gen_range <- function(from, to) {
    .Call(`_misccpp_gen_range`, from, to)
}

int_vec_insert <- function(vec, vals, pos) {
    .Call(`_misccpp_int_vec_insert`, vec, vals, pos)
}

int_mat_insert <- function(m, col, row, vals) {
    .Call(`_misccpp_int_mat_insert`, m, col, row, vals)
}

mat_to_mat_insert <- function(old_m, new_m, new_rows, new_cols, old_rows, old_cols) {
    .Call(`_misccpp_mat_to_mat_insert`, old_m, new_m, new_rows, new_cols, old_rows, old_cols)
}

mat_by_mat <- function(m, row, col) {
    .Call(`_misccpp_mat_by_mat`, m, row, col)
}

m_to_v_double <- function(m) {
    .Call(`_misccpp_m_to_v_double`, m)
}

lt_permute <- function(link_list, wave, name) {
    .Call(`_misccpp_lt_permute`, link_list, wave, name)
}

lt_gibbs <- function(data, y_samp, strata, n_strata, n_waves, total, chain_samples, chain_burnin, priors, param_init) {
    .Call(`_misccpp_lt_gibbs`, data, y_samp, strata, n_strata, n_waves, total, chain_samples, chain_burnin, priors, param_init)
}

rm_el <- function(input) {
    .Call(`_misccpp_rm_el`, input)
}

gen_pairs <- function(input) {
    .Call(`_misccpp_gen_pairs`, input)
}

extract <- function(m, r, c) {
    .Call(`_misccpp_extract`, m, r, c)
}

pareto_sim <- function(pop, mon, prob, iter) {
    .Call(`_misccpp_pareto_sim`, pop, mon, prob, iter)
}

assign_cluster <- function(points, centroids) {
    .Call(`_misccpp_assign_cluster`, points, centroids)
}

new_centroid <- function(points, assigned_c) {
    .Call(`_misccpp_new_centroid`, points, assigned_c)
}

kmean <- function(points, centroids, k, max_iter) {
    .Call(`_misccpp_kmean`, points, centroids, k, max_iter)
}

